### PR TITLE
Added setOrientation(), setReverse() and flushReverse() + Unchanged #include <OneMsTaskTimer.h>

### PR DESCRIPTION
**Pull request by rei-vilo**
Added **setOrientation()**, **setReverse()** and **flushReverse()**
Unchanged `#include <OneMsTaskTimer.h>`

### CODE REVIEW

**Comment by robertinant** [comment]
Rather than changing the LCD library we should change the OneMSTimer library to use the Clock module for EMT. I have the code ready, just need to do some testing. Will check it in later this week.

**Comment by rei-vilo** [comment]
Up to you! Actually, we can get rid of the extra library **OneMsTaskTimer** for the MSP432.

**Comment by robertinant** [comment]
Reason for doing it with OneMSTimer is that we can have one single LCD library that works on all LaunchPads. Easier to maintain that way.

**Comment by rei-vilo** [comment]
I've already modified the **OneMsTaskTimer** and **LCD_SharpBoosterPack_SPI** libraries with `#if defined()` `#else` `#endif` to ensure cross-compatibility.

**Pull request merged**
