### PR TITLE
Update SLFS.cpp, SLFS.h, keywords.txt to reflect new state of SLFS de…

### PR DESCRIPTION
**Pull request by spirilis**
…velopment.  Delete old SLFSDelete/SLFSTextFile examples, add 6 new examples that explore the library's use-cases and gotchas.

Energia MT support added after testing.

### CODE REVIEW

**Comment by spirilis** [comment]
All SLFS examples have been tested on:

msp430f5529 w/ CC3100
Tiva-C tm4c123g w/ CC3100
cc3200

msp432 w/ CC3100 using Energia MT**
cc3200 using Energia MT**

** - Examples run in a single thread; multi-threaded SLFS operations have not been tested, and I am assuming the SimpleLink WiFi API is threadsafe enough to make it work in case a user decides to tinker with SLFS files from multiple threads.

**Comment by rei-vilo** [comment]
>
** - Examples run in a single thread; multi-threaded SLFS operations have not been tested, and I am assuming the SimpleLink WiFi API is threadsafe enough to make it work in case a user decides to tinker with SLFS files from multiple threads.
>

Using a semaphore isn't a big deal with the [Galaxia Library](https://github.com/rei-vilo/GalaxiaLibrary)!

**Comment by robertinant** [comment]
Thanks @spirilis!

**Comment by spirilis** [comment]
Np!  On its way soon to come will be https://github.com/spirilis/SLHTTPD ..... then the SimpleLink's full featureset will be accessible!

**Pull request merged**
