### PR TITLE
Energia non EMT for RedBearLab CC3200 Boards

### PR DESCRIPTION
**Pull request by rei-vilo**
Energia non EMT for RedBearLab CC3200 and RedBearLab WiFi Mini boards

### CODE REVIEW

**Comment by robertinant** [comment]
Awesome @rei-vilo! Thanks for the pull!!

**Comment by flety-emmanuel** [comment]
could someone explain to me what "non EMT" means please ? thanks

**Comment by rei-vilo** [comment]
EMT stands for Energia Multi-Tasking.

Basically, non-EMT means standard Wiring-based sketch.

**Comment by flety-emmanuel** [comment]
thank you very much

**Pull request merged**
