### PR TITLE
Energia MT: Event (with choice of event number), Semaphore, Mailbox, Timer, Clock, SWI, Task Libraries and Main setup()

### PR DESCRIPTION
**Pull request by rei-vilo**
RTOS libraries for Energia MT 0101E0016 

* Event library with choice of event number `Event_Id_00` ... `Event_Id_31`
* Semaphore library
* Mailbox library
* Timer library —*see limitations*
* Clock library
* Use of `rtosGlobals.h` for global variables
* Optional main setup called `rtosSetup()`
* SWI library
* SWI with trigger library
* Task library

### CODE REVIEW

**Comment by rei-vilo** [comment]
To be sorted: more than one initialisation the semaphore —i.e. one `mySemaphore.begin(1);` on each task file `setup()`— may cause issues.

**Comment by robertinant** [comment]
Awesome pull request! One thing is that emt directory was deleted in this pull request so I can not pull it in as is. Can you put the emt directory back and update the pull request please?

**Comment by rei-vilo** [comment]
See commit 1cb9693!

**Comment by rei-vilo** [comment]
Pull request with emt link replaced by #643 and closed.

**Pull request closed without merging**
