### PR TITLE
Add protection

### PR DESCRIPTION
**Pull request by solexious**
Add ifndef protection to EthernetUdp.h

### CODE REVIEW

**Comment by spirilis** [comment]
Looks good to me ... I noticed EthernetClient.h and EthernetServer.h, along with Ethernet.h, already have these ifndef protections (and all in lowercase as this example shows).  Probably a small oversight since I don't think many of us play with the UDP code much. (paging @robertinant )

**Comment by solexious** [comment]
Was trying to get an arduino Artnet library working with Energia and the lack of the indef protection was giving me compile errors.

Hope the pull request is useful, its my first "real" one for an oss project :)

**Comment by robertinant** [comment]
Thanks for the pull request @solexious. Unfortunately ethernet_h is already used for Ethernet.h. Can you change it to ethernetudp_h and resubmit?

Thanks!

Robert

**Comment by spirilis** [comment]
Oh geez, didn't notice that!

**Comment by solexious** [comment]
Will do!

**Pull request closed without merging**
