### PR TITLE
Include SLFS with CC3200/CC3100 WiFi library

### PR DESCRIPTION
**Pull request by spirilis**
This library provides access to the SimpleLink API for Serial Flash on the CC3200 and CC3100 chips.

### CODE REVIEW

**Comment by robertinant** [comment]
Thanks for the this awesome addition!

**Comment by spirilis** [comment]
Oh my, there have been a lot of updates since this I think!  I'll make a new pullreq soon :)

**Comment by rei-vilo** [comment]
@spirilis Thank you for the nice Doxygen-based documentation!

**Comment by spirilis** [comment]
@rei-vilo FYI @robertinant actually pulled in a really old revision of the SLFS library, but forthcoming will be another pullreq with the new-and-improved version!

**Pull request merged**
