### PR TITLE
Changed private to protected in WiFiClient.h

### PR DESCRIPTION
**Pull request by honteng**

### CODE REVIEW

**Comment by honteng** [comment]
This pull-req is related to 
https://github.com/energia/Energia/issues/627

The change is very simple.

It would be great to be merged soon.

**Comment by honteng** [comment]
Just I want to clarify this patch purpose.

---
We want to release our company service SDK with SSL connection, but we have to pass root CA files to use SSL correctly.

I know still SSL connection implementation in WiFiClient is in progress, but we want to release our SDK before SSL connection implementation is ready in WiFiClient.

If properties are "protected", then our own SDK class can derive from WiFiClient. And the child class can access to SSL and socket related properties inside the class. Once WiFiClient class implementation for SSL is ready, we will change our SDK.

We don't want to ask developers to apply patch or change WiFiClient code directly only for our service.
---
Here is our code. https://github.com/moderepo/cc3200

**Comment by spirilis** [comment]
@robertinant Look legit so far? If so we can pull it in... I don't see any reason not to right now.

**Comment by honteng** [comment]
@spirilis @robertinant Yes, I believe it's legit and no major issue about this change. Can you guys merge this?

**Comment by robertinant** [comment]
I am fine with pulling it in.

**Comment by honteng** [comment]
Thanks, guys!

**Pull request merged**
